### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by Hongbin98** [abhi1kumar/DEVIANT#14]
Firstly, thanks for your excellent work!

When I try to validate my checkpoint on the KITTI validation set, i.e. `CUDA_VISIBLE_DEVICES=7 python -u tools/train_val.py --config=experiments/run_221.yaml --resume_model output/run_221/checkpoints/checkpoint_epoch_20.pth -e`.
I meet the FileNotFoundError: [Errno 2] No such file or directory: 'data/KITTI/kitti_split1/devkit/cpp/evaluate_object': 'data/KITTI/kitti_split1/devkit/cpp/evaluate_object'

The log is as follows:
```
Traceback (most recent call last):
  File "tools/train_val.py", line 155, in <module>
    main()
  File "tools/train_val.py", line 132, in main
    tester.test()
  File "/home/linhb/code/DEVIANT-main/code/lib/helpers/tester_helper.py", line 118, in test
    use_logging= True, logger= self.logger)
  File "/home/linhb/code/DEVIANT-main/code/lib/helpers/rpn_util.py", line 254, in evaluate_kitti_results_verbose
    results_obj.main = run_kitti_eval_script(eval_binary_path, results_data= stats_save_folder, gt_folder= gt_folder, lbls= lbls, use_40=True)
  File "/home/linhb/code/DEVIANT-main/code/lib/helpers/rpn_util.py", line 345, in run_kitti_eval_script
    _ = subprocess.check_output([eval_binary_path, results_data, gt_folder], stderr=devnull)
  File "/home/linhb/miniconda3/envs/DEVIANT/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/linhb/miniconda3/envs/DEVIANT/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/linhb/miniconda3/envs/DEVIANT/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/linhb/miniconda3/envs/DEVIANT/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'data/KITTI/kitti_split1/devkit/cpp/evaluate_object': 'data/KITTI/kitti_split1/devkit/cpp/evaluate_object'
```

Any help?

**Comment by abhi1kumar** [comment]
Hi @Hongbin98 
Thankyou for your interest in DEVIANT. It seems that the KITTI evaluation binaries are absent. 

Did you follow up our installation instructions line by line as in README? Specifically, did the following run successfully.
```
sudo apt-get install libopenblas-dev libboost-dev libboost-all-dev gfortran
sh data/KITTI/kitti_split1/devkit/cpp/build.sh
```

**Comment by Hongbin98** [comment]
Thanks for your timely reply!

It seems to be my fault to ignore this step. I will try this and fix this error.

**Comment by abhi1kumar** [comment]
If you find our repo useful, please consider supporting by starring it.

**Comment by Hongbin98** [comment]
Sure! :)

**Comment by Aangss** [comment]
Thank you for  your reply.  I will try to fix this error.
