### ISSUE TITLE
I'm new to 3D object detection . I meet some troubles, can you give me some advice? thanks！

### ISSUE THREAD

**Issue by Aangss** [abhi1kumar/DEVIANT#17]
INFO  ------ EVAL EPOCH 020 ------
Evaluation Progress: 100%|████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:54<00:00,  2.75s/it]
2023-10-07 15:28:18,751   INFO  ==> Saving results in output/config_run_201_a100_v0_1/result_20
Traceback (most recent call last):
  File "/home/ys/DEVIANT/code/tools/train_val.py", line 158, in <module>
    main()
  File "/home/ys/DEVIANT/code/tools/train_val.py", line 152, in main
    trainer.train()
  File "/home/ys/DEVIANT/code/lib/helpers/trainer_helper.py", line 87, in train
    self.eval_one_epoch()
  File "/home/ys/DEVIANT/code/lib/helpers/trainer_helper.py", line 207, in eval_one_epoch
    use_logging= True, logger= self.logger)
  File "/home/ys/DEVIANT/code/lib/helpers/rpn_util.py", line 254, in evaluate_kitti_results_verbose
    results_obj.main = run_kitti_eval_script(eval_binary_path, results_data= stats_save_folder, gt_folder= gt_folder, lbls= lbls, use_40=True)
  File "/home/ys/DEVIANT/code/lib/helpers/rpn_util.py", line 345, in run_kitti_eval_script
    _ = subprocess.check_output([eval_binary_path, results_data, gt_folder], stderr=devnull)
  File "/home/ys/.conda/envs/DEVIANT/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/ys/.conda/envs/DEVIANT/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/ys/.conda/envs/DEVIANT/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/ys/.conda/envs/DEVIANT/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'data/KITTI/kitti_split1/devkit/cpp/evaluate_object': 'data/KITTI/kitti_split1/devkit/cpp/evaluate_object'

**Comment by abhi1kumar** [comment]
Hi @Aangss 
Thankyou for your interest in DEVIANT. Your question is copy of #14 . Please see the [response](https://github.com/abhi1kumar/DEVIANT/issues/14#issuecomment-1698398836)

PS - In case you find our repository useful, please consider supporting by starring it.

**Comment by Aangss** [comment]
Thank you very much for your answer. I have solved this error and successfully trained to get the training model after 140 rounds, but I want to test it with images, how do I do it and is there a test demo?
![image](https://github.com/abhi1kumar/DEVIANT/assets/144333787/8a038121-cb18-459b-9969-c0d38378b1a0)

**Comment by abhi1kumar** [comment]
Check the [section](https://github.com/abhi1kumar/DEVIANT#qualitative-plotsvisualization) to generate qualitative results.
